// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7DLACh9iQjpyQ5336j_sgy3RXn_9Rq7U',
    appId: '1:563164723027:web:64fd1315087d385b5ad3a6',
    messagingSenderId: '563164723027',
    projectId: 'expansemate',
    authDomain: 'expansemate.firebaseapp.com',
    storageBucket: 'expansemate.appspot.com',
    measurementId: 'G-0P2PRC1SY9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2V0tU3Ka3fkgpctVg45x-4i5atUR8NDM',
    appId: '1:563164723027:android:b2cad73276f43e675ad3a6',
    messagingSenderId: '563164723027',
    projectId: 'expansemate',
    storageBucket: 'expansemate.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUa42gV8rvDowa297WFd0HfrhX8txoABc',
    appId: '1:563164723027:ios:cffde021b1d978d55ad3a6',
    messagingSenderId: '563164723027',
    projectId: 'expansemate',
    storageBucket: 'expansemate.appspot.com',
    iosBundleId: 'com.example.expanseMate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUa42gV8rvDowa297WFd0HfrhX8txoABc',
    appId: '1:563164723027:ios:cffde021b1d978d55ad3a6',
    messagingSenderId: '563164723027',
    projectId: 'expansemate',
    storageBucket: 'expansemate.appspot.com',
    iosBundleId: 'com.example.expanseMate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7DLACh9iQjpyQ5336j_sgy3RXn_9Rq7U',
    appId: '1:563164723027:web:3ad3283a2fe3f2645ad3a6',
    messagingSenderId: '563164723027',
    projectId: 'expansemate',
    authDomain: 'expansemate.firebaseapp.com',
    storageBucket: 'expansemate.appspot.com',
    measurementId: 'G-T7CM115J3M',
  );

}